### ISSUE TITLE
COVID-19 Growth Rate Prediction | UK graph is missing

### ISSUE THREAD

**Issue by jf908** [machine-learning-apps/covid19-dashboard#20]
For COVID-19 Growth Rate Prediction's predicted cases, the UK is missing from the graphs because n_countries is not divisible by 3.

Maybe use `nrows=n_countries // 3 + 1` or some solution which doesn't show empty graphs?

**Comment by hamelsmu** [comment]
ccc: @twiecki ☝️  Maybe you have some thoughts

**Comment by hamelsmu** [comment]
@jf908 if you would like to make a PR to fix this noteobook, please do so, I can use the help!  

https://github.com/machine-learning-apps/covid19-dashboard/blob/master/_notebooks/2020-03-15-covid19_growth_bayes.ipynb

**Comment by hamelsmu** [comment]
Actually nm I can fix this, not a big deal
