### ISSUE TITLE
Figure width too big?

### ISSUE THREAD

**Issue by jbao** [machine-learning-apps/covid19-dashboard#41]
First off, really interesting work;-) I noticed that certain figures, e.g. 
https://covid19dashboards.com/growth-bayes/
are too wide to fit into the page (both desktop and mobile), any quick fix?

**Comment by hamelsmu** [comment]
Yeah I could use some help with this.  Any ideas?  I don't know how to fix this easily.  I could stack the charts vertically but I think that could be confusing.  

Thoughts?

**Comment by hamelsmu** [comment]
I addressed this and made the chart you identified a smaller width.
