### ISSUE TITLE
load_covid_data'

### ISSUE THREAD

**Issue by kassouna** [machine-learning-apps/covid19-dashboard#47]
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-6-3b7a210c12d0> in <module>()
      9 import pymc3 as pm
     10 import altair as alt
---> 11 import load_covid_data
     12 
     13 sns.set_context('talk')

ModuleNotFoundError: No module named 'load_covid_data'

---------------------------------------------------------------------------
NOTE: If your import is failing due to a missing package, you can
manually install dependencies using either !pip or !apt.

**Comment by hamelsmu** [comment]
hmmm.  that's because that is coming from a python file that is relative to the notebook.  I guess I can fix this

**Comment by hamelsmu** [comment]
@kassouna I changed the code.  Hopefully works for you now!
