### ISSUE TITLE
SARS and COVID-19 death proportions are identical

### ISSUE THREAD

**Issue by noleti** [machine-learning-apps/covid19-dashboard#9]
On https://covid19dashboards.com/comparitive-analysis/#Deaths, SARS and COVID-19 proportions are identical. I assume this is an error, as e.g., Italy had 0 deaths to SARS in 2002-2003.

**Comment by noleti** [comment]
in particular in [12] c_lat_grp is used twice (plot 1 and 3), the second use should be s_lat_grp I assume.

**Comment by hamelsmu** [comment]
Thanks for reporting this.  I fixed this in c51d916ad15ca005a2510c76da7874021d20fd70

cc: @imdevskp
